-- Jalankan seluruh skrip ini di Supabase → SQL Editor → Run.
-- Aman dijalankan ulang (DROP POLICY IF EXISTS).

-- ========== TABLE products ==========
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  title text not null,
  price numeric not null,
  category text not null,
  series text,
  series_name text,
  character text,
  character_name text,
  size text,
  finish text,
  notes text,
  image_url text not null
);

alter table public.products enable row level security;

drop policy if exists "public read products" on public.products;
create policy "public read products"
on public.products
for select
using (true);

drop policy if exists "public insert products" on public.products;
create policy "public insert products"
on public.products
for insert
with check (true);

-- ========== STORAGE bucket ==========
-- Buat bucket storage untuk gambar produk
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

-- Pastikan bucket publik (URL .../object/public/... bisa dibuka di browser)
update storage.buckets set public = true where id = 'product-images';

-- ========== STORAGE policies ==========
-- Hapus policy lama jika ada
drop policy if exists "storage read product images" on storage.objects;
drop policy if exists "storage insert product images" on storage.objects;
drop policy if exists "storage update product images" on storage.objects;
drop policy if exists "storage delete product images" on storage.objects;
drop policy if exists "anon read product images" on storage.objects;
drop policy if exists "anon upload product images" on storage.objects;
drop policy if exists "auth read product images" on storage.objects;
drop policy if exists "auth upload product images" on storage.objects;

-- Buat policy baru untuk anon key (public read & write)
create policy "storage read product images"
on storage.objects
for select
using (bucket_id = 'product-images');

create policy "storage insert product images"
on storage.objects
for insert
with check (bucket_id = 'product-images');

create policy "storage update product images"
on storage.objects
for update
using (bucket_id = 'product-images');

create policy "storage delete product images"
on storage.objects
for delete
using (bucket_id = 'product-images');

-- Policy untuk anon key (bisa upload & baca gambar)
create policy "anon read product images"
on storage.objects
for select
using (true);

create policy "anon upload product images"
on storage.objects
for insert
with check (true);

-- Policy untuk auth user (opsional, jika menggunakan auth)
create policy "auth read product images"
on storage.objects
for select
using (true);

create policy "auth upload product images"
on storage.objects
for insert
with check (true);
