-- Jalankan seluruh skrip ini di Supabase → SQL Editor → Run.
-- Aman dijalankan ulang (DROP POLICY IF EXISTS).

-- ========== TABLE products ==========
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  title text not null,
  price numeric not null,
  category text not null,
  series text,
  series_name text,
  character text,
  character_name text,
  size text,
  finish text,
  notes text,
  image_url text not null
);

alter table public.products enable row level security;

drop policy if exists "public read products" on public.products;
create policy "public read products"
on public.products
for select
using (true);

drop policy if exists "public insert products" on public.products;
drop policy if exists "Only admins can insert products" on public.products;
create policy "Only admins can insert products"
on public.products
for insert
with check (
  exists (
    select 1 from public.site_admins 
    where email = auth.jwt()->>'email'
  )
);

drop policy if exists "Only admins can update products" on public.products;
create policy "Only admins can update products"
on public.products
for update
using (
  exists (
    select 1 from public.site_admins 
    where email = auth.jwt()->>'email'
  )
);

drop policy if exists "Only admins can delete products" on public.products;
create policy "Only admins can delete products"
on public.products
for delete
using (
  exists (
    select 1 from public.site_admins 
    where email = auth.jwt()->>'email'
  )
);

-- ========== STORAGE bucket ==========
-- Buat bucket storage untuk gambar produk
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

-- Pastikan bucket publik (URL .../object/public/... bisa dibuka di browser)
update storage.buckets set public = true where id = 'product-images';

-- ========== STORAGE policies ==========
-- Hapus policy lama jika ada
drop policy if exists "storage read product images" on storage.objects;
drop policy if exists "storage insert product images" on storage.objects;
drop policy if exists "storage update product images" on storage.objects;
drop policy if exists "storage delete product images" on storage.objects;
drop policy if exists "anon read product images" on storage.objects;
drop policy if exists "anon upload product images" on storage.objects;
drop policy if exists "auth read product images" on storage.objects;
drop policy if exists "auth upload product images" on storage.objects;
drop policy if exists "Only admins can insert storage" on storage.objects;
drop policy if exists "Only admins can update storage" on storage.objects;
drop policy if exists "Only admins can delete storage" on storage.objects;

-- Buat policy baru untuk anon key (public read saja)
create policy "storage read product images"
on storage.objects
for select
using (bucket_id = 'product-images');

-- Otorisasi upload hanya untuk admin
create policy "Only admins can insert storage"
on storage.objects
for insert
with check (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.site_admins 
    where email = auth.jwt()->>'email'
  )
);

-- Otorisasi update hanya untuk admin
create policy "Only admins can update storage"
on storage.objects
for update
using (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.site_admins 
    where email = auth.jwt()->>'email'
  )
);

-- Otorisasi delete hanya untuk admin
create policy "Only admins can delete storage"
on storage.objects
for delete
using (
  bucket_id = 'product-images'
  and exists (
    select 1 from public.site_admins 
    where email = auth.jwt()->>'email'
  )
);
